old/projects_0405_02/autoslider/boards/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt

app_name = 'boards'

urlpatterns = [
    path('list/', views.BoardListView.as_view(), name='board_list'),  # board_list 기본 & 목록
    path('favorite/', views.FavoriteBoardListView.as_view(), name='favorite_board_list'),
    path('new/', views.BoardCreateView.as_view(), name='board_create'),
    path('<int:pk>/', views.BoardDetailView.as_view(), name='board_detail'),
    path('<int:pk>/modifav', views.modifiy_favorite, name='modifiy_favorite'),
    # path('<int:pk>/update/', views.BoardUpdateView.as_view(), name='board_update'),
    # path('<int:pk>/delete/', views.BoardDeleteView.as_view(), name='board_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#  MEDIA_URL로 접근하면 MEDIA_ROOT 경로에 저장된 파일을 서비스하도록 설정함. 이제 파일 업로드 뷰에서 파일을 업로드하면 MEDIA_ROOT에 파일이 저장되고, 데이터베이스에는 파일 경로가 저장됨.

handler403 = 'django.views.defaults.permission_denied'
handler404 = 'django.views.defaults.page_not_found'
handler500 = 'django.views.defaults.server_error'

old/projects_0405_02/autoslider/templates/common/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="profile container-fluid">
    <h1 class="logo">
        <a href="{% url 'common:login' %}"><img id="logo_img" src="{% static 'img/logo3.png' %}" class="img-fluid"></a>
    </h1>
    <div class="profile_content ">
        <form method="post" action="{% url 'common:profile' %}" id="profile_form" onsubmit="{% url 'boards:board_list' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
            {% if new_password1 != new_password2 %}
                <div class="text-bg-warning p-3" onclick="validchk()">"새 비밀번호"와 "새 비밀번호(확인)"이 일치하지 않습니다.</div>
            {% endif %}
            <div class="input-group mb-3">
                <span class="input-group-text" id="username">아이디</span>
                <input name="username" type="text" class="form-control" value="{{ form.instance.username }}" aria-label="Username" aria-describedby="basic-addon1" required readonly>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="phone">핸드폰</span>
                <input name="phone" type="text" class="form-control" value="{{ form.instance.phone }}" aria-label="Username" aria-describedby="basic-addon1" required>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="email">이메일</span>
                <input name="email" type="text" class="form-control" value="{{ form.instance.email }}" aria-label="Username" aria-describedby="basic-addon1" required>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="nickname">닉네임</span>
                <input  name="nickname" type="text" class="form-control" value="{{ form.instance.nickname }}" aria-label="Username" aria-describedby="basic-addon1" required>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="current_password">기존 비밀번호</span>
                <input name="current_password" type="password" class="form-control" aria-label="Username" aria-describedby="basic-addon1" required>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="new_password1">새 비밀번호</span>
                <input name="new_password1" type="password" class="form-control" aria-label="new_password1" aria-describedby="basic-addon1" minlength="8" required>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="new_password2">새 비밀번호(확인)</span>
                <input name="new_password2" type="password" class="form-control" aria-label="new_password2" aria-describedby="basic-addon1" required>
            </div>
            <div id="login_div">
                <button type="submit" form="profile_form" class="btn btn-secondary btn-lg">변경하기</button>
            </div>
        </form>
    </div>
</div>
<!-- 푸터 -->
{% include 'footer.html' %}
{% endblock %}
<script>
const password = document.getElementById('new_password1');
const confirm_password = document.getElementById('new_password2');

pwdvalidchk() {
  if (password.value !== confirm_password.value) {
    alert("'새 비밀번호'와 '새 비밀번호(확인)'이 다릅니다.");
    return false;
  }
});
</script>
</body>
</html>