old/projects_0406/autoslider/boards/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'boards'

urlpatterns = [
    path('list/', views.BoardListView.as_view(), name='board_list'),  # board_list 기본 & 목록
    path('favorite/', views.FavoriteBoardListView.as_view(), name='favorite_board_list'),
    path('new/', views.BoardCreateView.as_view(), name='board_create'),
    path('<int:pk>/', views.BoardDetailView.as_view(), name='board_detail'),
    path('<int:pk>/modifav', views.modifiy_favorite, name='modifiy_favorite'),
    path('<int:pk>/update/', views.BoardUpdateView.as_view(), name='board_update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#  MEDIA_URL로 접근하면 MEDIA_ROOT 경로에 저장된 파일을 서비스하도록 설정함. 이제 파일 업로드 뷰에서 파일을 업로드하면 MEDIA_ROOT에 파일이 저장되고, 데이터베이스에는 파일 경로가 저장됨.

old/projects_0406/autoslider/common/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views  # login&logout
from . import views
from boards.views import BoardListView

app_name = 'common'

urlpatterns = [
    # path('', views.IndexView.as_view(), name='main'),
    path('', views.IndexView.as_view(template_name='boards/board_list.html')),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(template_name='common/signup.html'), name='signup'),
    path('profile/', views.profile, name='profile'),
    path('produce/', views.produce, name='produce'),
]

old/projects_0406/autoslider/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls', 'common')), # '/' 에 해당되는 path
    path('', include('boards.urls', 'boards')),
]

old/projects_0406/autoslider/common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

class CustomUser(AbstractUser):
    nickname = models.CharField(max_length=20, default='')
    phone_regex = RegexValidator(regex=r'^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})$') # 정규식 011-123-4567 혹은 010-1234-5678 기준
    phone = models.CharField(validators=[phone_regex], max_length=13, unique=True, verbose_name='phone', null=False, blank=False) # 010-1234-5678 기준 갯수

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['phone', 'nickname', 'email']
    first_name = None
    last_name = None

    def __str__(self):
        return self.username

old/projects_0406/autoslider/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class SignupForm(UserCreationForm):
    nickname = forms.CharField(max_length=20)
    class Meta: #메타 안에 있는 모델과 필드들을 커스텀 유저에 맞게 수정 작업하는 것
        model=CustomUser
        fields= ['username', 'password1', 'password2', 'nickname', 'phone', 'email']


class ChangeForm(UserChangeForm):
# 회원 정보 수정
    nickname = forms.CharField(max_length=20)
    class Meta(UserChangeForm):
        model = CustomUser
        fields = ['username', 'password', 'nickname', 'phone', 'email']

old/projects_0406/autoslider/common/views.py
from django.views import generic
# from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.forms import PasswordChangeForm
from .forms import SignupForm
from .forms import ChangeForm


# Create your views here.
class IndexView(LoginRequiredMixin, generic.View):
    template_name = 'boards/board_list.html'
    def get(self, request):
        return render(request, 'boards/board_list.html')

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('common:login')
        else:
            return redirect('boards:board_list')


# 로그인
class LoginView(BaseLoginView):
    template_name = 'common/login.html'
    authentication_form = SignupForm
    redirect_authenticated_user = True

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        else:
            return reverse_lazy('boards:board_list')


# 회원가입
class SignupView(CreateView):
    form_class = SignupForm
    template_name = 'common/signup.html'
    success_url = reverse_lazy('common:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        form.save() # 회원 정보 저장
        return response

# 프로필 수정
def profile(request):
    if request.method == 'POST':
        form = ChangeForm(request.POST, instance=request.user)
        form_pw = PasswordChangeForm(request.user, request.POST)
        if form.is_valid() and form_pw.is_valid():
            form.save()
            form_pw.save()
            new_password1 = form_pw.cleaned_data.get('new_password1')
            user = authenticate(password=new_password1)  # 사용자 인증
            auth_login(request, user)  # 로그인
            return redirect('common:login')
        else:
            new_password1 = request.POST.get('new_password1')
            new_password2 = request.POST.get('new_password2')
            context = {'new_password1': new_password1, 'new_password2': new_password2}
            return render(request, 'common/profile.html', context)
    else:
        form = ChangeForm(instance=request.user)
        form_pw = PasswordChangeForm(request.user)
        return render(request, 'common/profile.html', {'form':form, 'form_pw':form_pw})

def produce(request):
    return render(request, 'common/produce.html')

old/projects_0406/autoslider/templates/common/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- S: login.html -->
<div class="container my-3">
    <h1 id ="logo_div" class="logo">
        <img id="logo_img" src="{% static 'img/logo_1.png' %}" class="img-fluid mx-auto d-block" alt="AutoSlider 로고">
    </h1>
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div id="id_div" class="input-group mb-3">
            <label for="username" class="userform_label">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}" required>
        </div>
        <div id="password_div" class="input-group mb-3">
            <label for="password" class="userform_label">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}" required>
        </div>
        {% if user.is_authenticated %}
        <div id="signup_div">
            <button id="signup_button" type="submit" class="btn btn-primary btn-lg">로그인</button>
        <div>
        {% else %}
        <div id="signup_div">
            <button id="signup_button" type="submit" class="btn btn-secondary btn-lg">회원가입</button>
        </div>
        {% endif%}
    </form>
</div>
<!-- E: login.html -->
{% endblock %}

old/projects_0406/autoslider/templates/common/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    #login_div {
        width:200px;
        position:relative;
        left: 80px;
    }
    #pre_div {
        width:200px;
        position:relative;
        left: 230px;
        bottom:48px;
    }
</style>
<div class="profile container-fluid">
    <h1 class="logo">
        <a href="{% url 'common:login' %}"><img id="logo_img" src="{% static 'img/logo3.png' %}" class="img-fluid"></a>
    </h1>
    <div class="profile_content ">
        <form method="post" action="{% url 'common:profile' %}" id="profile_form">
    {% csrf_token %}
        {% if new_password1 != new_password2 %}
            <div class="text-bg-warning p-3" onclick="validchk()">"새 비밀번호"와 "새 비밀번호(확인)"이 일치하지 않습니다.</div>
        {% endif %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="username">아이디</span>
            <input name="username" type="text" class="form-control" value="{{ user.username }}" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="phone">핸드폰</span>
            <input name="phone" type="text" class="form-control" value="{{ user.phone }}" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="email">이메일</span>
            <input name="email" type="text" class="form-control" value="{{ user.email }}" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="nickname">닉네임</span>
            <input  name="nickname" type="text" class="form-control" value="{{ user.nickname }}" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="old_password">기존 비밀번호</span>
            <input name="old_password" type="password" class="form-control" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="new_password1">새 비밀번호</span>
            <input name="new_password1" type="password" class="form-control" aria-label="new_password1" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="new_password2">새 비밀번호(확인)</span>
            <input name="new_password2" type="password" class="form-control" aria-label="new_password2" aria-describedby="basic-addon1">
        </div>
        </form>
        <div id="login_div">
            <button type="submit" form="profile_form" class="btn btn-secondary btn-lg">변경하기</button>
        </div>
        <div id="pre_div">
            <button onclick="window.location.href='{% url 'boards:board_list' %}'" type="button" class="btn btn-secondary btn-lg">이전으로</button>
        </div>
    </div>
</div>
<!-- 푸터 -->
{% include 'footer.html' %}
{% endblock %}
<script>
const password = document.getElementById('new_password1');
const confirm_password = document.getElementById('new_password2');

pwdvalidchk() {
  if (password.value !== confirm_password.value) {
    alert("'새 비밀번호'와 '새 비밀번호(확인)'이 다릅니다.");
    return false;
  }
});
</script>
</body>
</html>

old/projects_0406/autoslider/templates/common/signup.html
{% block content %}
<!-- S: login.html -->
<div class="container my-3 userform">
    <h1>회원 가입</h1>
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username" class="userform_label">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}" title="20자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다." required>
        </div>
        <div class="mb-3">
            <label for="password1" class="userform_label">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}" minlength="8" pattern="^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,16}$" title="비밀번호는 최소 8자여야 하며, 숫자 및 영문과 특수문자($@$!%*#?&) 조합이어야 합니다. 또한 다른 개인정보와 유사해서는 안됩니다." required>
        </div>
        <div class="mb-3">
            <label for="password2" class="userform_label">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}" minlength="8" pattern="^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,16}$" placeholder="확인을 위해 이전과 동일한 비밀번호를 입력하세요." required>
        </div>
        <div class="mb-3">
            <label for="nickname" class="userform_label">닉네임</label>
            <input type="text" class="form-control" name="nickname" id="username" value="{{ form.nickname.value|default_if_none:'' }}" title="20자 이하 문자, 숫자 만 가능합니다." required>
        </div>
        <div class="mb-3">
            <label for="phone" class="userform_label">휴대폰번호</label>
            <input type="text" class="form-control" name="phone" id="phone" value="{{ form.phone.value|default_if_none:'' }}" pattern="^01([016789])([0-9]{7,8})$" placeholder="01012345678 형식으로 입력해주세요." required>
        </div>
        <div class="mb-3">
            <label for="email" class="userform_label">이메일</label>
            <input type="email" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}" placeholder="example@test.com" required>
        </div>
        <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
</div>
<!-- E: login.html -->
{% endblock %}